modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/Cucumber/issues"
    modId="cucumber"
    version="${file.jarVersion}"
    # logoFile="examplemod.png"
    displayURL="https://blakesmods.com/cucumber"
    displayName="Cucumber Library"
    updateJSONURL="https://api.blakesmods.com/v2/mods/cucumber/1.20/updates"
    authors="BlakeBr0"
    description='''
    A library of shared code that all of my mods depend on.
    '''

    [[dependencies.cucumber]]
        modId="forge"
        mandatory=true
        versionRange="[47.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.cucumber]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"